# pylint: disable=line-too-long,invalid-name
import copy
import enum
import os
import pathlib
import shlex
import shutil
import subprocess
import textwrap
import urllib.parse
from collections import ChainMap
from functools import reduce
from typing import Any, Dict, Generator, List, MutableMapping, Union

import yaml
from dagster import (
    AssetExecutionContext,
    AssetIn,
    AssetKey,
    AssetMaterialization,
    AssetOut,
    AssetsDefinition,
    AssetSpec,
    EnvVar,
    MetadataValue,
    Output,
    asset,
    multi_asset,
)
from docker_compose_graph.utils import (
    deep_merge,
)
from OpenStudioLandscapes.engine.common_assets import (
    cmd,
    compose,
    docker_compose_graph,
    feature,
    feature_out,
    group_in,
    group_out,
)
from OpenStudioLandscapes.engine.config.models import (
    ConfigEngine,
    DockerConfigModel,
    SudoMethod,
)
from OpenStudioLandscapes.engine.base.configurable_resources.docker_registry_resource import DockerRegistryConfigurableResource
from OpenStudioLandscapes.engine.constants import (
    ASSET_HEADER_BASE,
    ConfigParent,
)
from OpenStudioLandscapes.engine.enums import (
    DockerComposePolicies,
)
from OpenStudioLandscapes.engine.link.models import OpenStudioLandscapesFeatureIn
from OpenStudioLandscapes.engine.policies.retry import build_docker_image_retry_policy
from OpenStudioLandscapes.engine.utils import (
    create_image,
    get_apt_install_str,
    get_copy_str,
    get_docker_compose_names,
    get_docker_run_cmd,
    get_image_metadata,
    get_pip_install_str,
    get_relative_path_via_common_root,
)
from OpenStudioLandscapes.engine.utils.docker.compose_dicts import (
    get_network_dicts,
)

from OpenStudioLandscapes.Deadline_10_2 import (
    ASSET_HEADER,
    config,
    dist,
)

# Todo:
#  - [ ] consolidate build_docker_image* assets into 1
#  - [ ] don't include the installers inside the images
#  - [ ] [Investigate Rez in Deadline](https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/event-rez.html)
#  - [x] Use REST API instead of `deadlinecommand`

# - [Arbitrary Command Line Jobs](https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/manual-submission.html#arbitrary-command-line-jobs)
# - [Maintenance Jobs](https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/manual-submission.html#maintenance-jobs)
# - [Creating Job Submission Files](https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/manual-submission.html#creating-job-submission-files)

# https://github.com/yaml/pyyaml/issues/722#issuecomment-1969292770
yaml.SafeDumper.add_multi_representer(
    data_type=enum.Enum,
    representer=yaml.representer.SafeRepresenter.represent_str,
)


cmd: AssetsDefinition = cmd.get_feature__cmd(
    ASSET_HEADER=ASSET_HEADER,
)

CONFIG: AssetsDefinition = feature.get_feature__CONFIG(
    ASSET_HEADER=ASSET_HEADER,
    CONFIG_STR=config.models.CONFIG_STR,
    search_model_of_type=config.models.Config,
)

feature_in: AssetsDefinition = group_in.get_feature_in(
    ASSET_HEADER=ASSET_HEADER,
    ASSET_HEADER_BASE=ASSET_HEADER_BASE,
    ASSET_HEADER_FEATURE_IN={},
)

group_out: AssetsDefinition = group_out.get_group_out(
    ASSET_HEADER=ASSET_HEADER,
)


docker_compose_graph: AssetsDefinition = docker_compose_graph.get_docker_compose_graph(
    ASSET_HEADER=ASSET_HEADER,
)


compose: AssetsDefinition = compose.get_compose(
    ASSET_HEADER=ASSET_HEADER,
)


feature_out_v2: AssetsDefinition = feature_out.get_feature_out_v2(
    ASSET_HEADER=ASSET_HEADER,
)


# Produces
# - feature_in_parent
# - CONFIG_PARENT
# if ConfigParent is or type FeatureBaseModel
feature_in_parent: Union[AssetsDefinition, None] = group_in.get_feature_in_parent(
    ASSET_HEADER=ASSET_HEADER,
    config_parent=ConfigParent,
)


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def connection_ini(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:

    env: Dict = CONFIG.env

    # @formatter:off
    connection_ini = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        [Connection]
        AlternatePort=0
        Authenticate=False
        DatabaseName={MONGO_DB_NAME}
        DbType=MongoDB
        EnableSSL=False
        Hostname={MONGO_DB_HOST}
        PasswordHash=
        Port={MONGO_DB_PORT_CONTAINER}
        ReplicaSetName=
        SplitDB=False
        Username=
        Version=10
        StorageAccess=Database
        CACertificatePath=
        ClientsThatPreferSecondaryReplicas=
        """).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        MONGO_DB_NAME=CONFIG.deadline_10_2_MONGO_DB_NAME,
        MONGO_DB_HOST=CONFIG.deadline_10_2_MONGO_DB_HOST,
        MONGO_DB_PORT_CONTAINER=CONFIG.deadline_10_2_MONGO_DB_PORT_CONTAINER,
    )
    # @formatter:on

    deadline_connection_ini = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "configs",
        "DeadlineRepository10",
        "settings",
        "connection.ini",
    ).expanduser()

    deadline_connection_ini.parent.mkdir(parents=True, exist_ok=True)

    with open(deadline_connection_ini, "w") as fw:
        fw.write(connection_ini)

    yield Output(deadline_connection_ini)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(
                deadline_connection_ini
            ),
            "connection_ini": MetadataValue.md(f"```\n{connection_ini}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def deadline_ini(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    # @formatter:off

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    deadline_ini = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        # Full Documentation
        # https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/client-config.html#client-config-conn-server-ref-label
        [Deadline]
        # # For Remote
        # ConnectionType=Remote
        # ProxyRoot=deadline-rcs-runner-10-2.{OPENSTUDIOLANDSCAPES__DOMAIN_LAN}:8888
        # ProxyRoot0=deadline-rcs-runner-10-2.{OPENSTUDIOLANDSCAPES__DOMAIN_LAN}:8888
        # ###
        # #################################
        # For Repository
        ConnectionType=Repository
        NetworkRoot=/opt/Thinkbox/DeadlineRepository10
        NetworkRoot0=/opt/Thinkbox/DeadlineRepository10
        ###
        WebServiceHttpListenPort={WEBSERVICE_HTTP_PORT_CONTAINER}
        WebServiceTlsListenPort=0
        WebServiceTlsServerCert=
        WebServiceTlsCaCert=
        WebServiceTlsAuth=False
        WebServiceClientSSLAuthentication=NotRequired
        HttpListenPort={RCS_HTTP_PORT_CONTAINER}
        TlsListenPort=0
        LicenseMode=LicenseFree
        Region=
        LauncherListeningPort=17000
        LauncherServiceStartupDelay=60
        AutoConfigurationPort=17001
        SlaveStartupPort=17003
        LicenseForwarderListeningPort=17004
        SlaveDataRoot=
        NoGuiMode=false
        AutoUpdateOverride=false
        IncludeRCSInLauncherMenu=true
        DbSSLCertificate=
        AutoUpdateBlock=NotBlocked

        # Controlled by Docker
        LaunchRemoteConnectionServerAtStartup=false
        KeepRemoteConnectionServerRunning=false
        LaunchPulseAtStartup=false
        KeepPulseRunning=false
        LaunchBalancerAtStartup=false
        KeepBalancerRunning=false
        KeepWebServiceRunning=false
        KeepWorkerRunning=false
        RestartStalledSlave=false
        LaunchLicenseForwarderAtStartup=false
        KeepLicenseForwarderRunning=false
        LaunchSlaveAtStartup=false
        """).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        OPENSTUDIOLANDSCAPES__DOMAIN_LAN=config_engine.openstudiolandscapes__domain_lan,
        WEBSERVICE_HTTP_PORT_CONTAINER=CONFIG.deadline_10_2_WEBSERVICE_HTTP_PORT_CONTAINER,
        RCS_HTTP_PORT_CONTAINER=CONFIG.deadline_10_2_RCS_HTTP_PORT_CONTAINER,
    )
    # @formatter:on

    deadline_client_ini = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "configs",
        "Deadline10",
        "deadline.ini",
    ).expanduser()

    deadline_client_ini.parent.mkdir(parents=True, exist_ok=True)

    with open(deadline_client_ini, "w") as fw:
        fw.write(deadline_ini)

    yield Output(deadline_client_ini)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(deadline_client_ini),
            "connection_ini": MetadataValue.md(f"```\n{deadline_ini}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_install_repository(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[List] | AssetMaterialization, None, None]:
    """ """

    # Todo
    #  - [ ] skip installation if already installed

    deadline_command = [
        "/installers/DeadlineRepository.run",
        "--mode",
        "unattended",
        "--prefix",
        "/opt/Thinkbox/DeadlineRepository10",
        "--setpermissions",
        "true",
        "--dbtype",
        "MongoDB",
        "--installmongodb",
        "false",
        "--dbhost",
        str(CONFIG.deadline_10_2_MONGO_DB_HOST),
        "--dbport",
        str(CONFIG.deadline_10_2_MONGO_DB_PORT_HOST),
        "--dbname",
        str(CONFIG.deadline_10_2_MONGO_DB_NAME),
        "--dbauth",
        "false",
        "--dbssl",
        "false",
        "--installSecretsManagement",
        "false",
        "--importrepositorysettings",
        "false",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "deadline_command_install_repository": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_install_repository",
                ]
            ),
        ),
    },
)
def deadline_script_install_repository(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    deadline_command_install_repository: List,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    install_repository = dict()

    # Todo:
    #  - [ ] textwrap.dedent script str

    install_repository["exe"] = shutil.which("bash")
    install_repository["script"] = str()

    # https://github.com/michimussato/kitsu-setup/blob/main/README_KITSU.md
    install_repository["script"] += "#!/bin/bash\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += "if [[ -n \"$( ls -A '/opt/Thinkbox/DeadlineRepository10')\" ]]; then\n"
    install_repository[
        "script"
    ] += "    echo /opt/Thinkbox/DeadlineRepository10 is not empty.\n"
    install_repository["script"] += "    echo Using existing Installation.\n"
    install_repository["script"] += "    echo Quit.\n"
    install_repository["script"] += "    exit 0;\n"
    install_repository["script"] += "fi\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += "echo /opt/Thinkbox/DeadlineRepository10 is empty or does not exist.\n"
    install_repository["script"] += "echo Installing Repository...\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += f"{shlex.join(deadline_command_install_repository)}\n"
    install_repository["script"] += "\n"
    install_repository["script"] += "echo Repository installed.\n"
    install_repository["script"] += "\n"
    install_repository["script"] += "exit 0\n"

    install_repository_script = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "__".join(context.asset_key.path),
        "install_repository.sh",
    )

    install_repository_script.parent.mkdir(parents=True, exist_ok=True)

    with open(
        file=install_repository_script,
        mode="w",
    ) as sh_install_repository:
        sh_install_repository.write(install_repository["script"])

    yield Output(install_repository_script)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(
                install_repository_script
            ),
            "dict_install_repository": MetadataValue.json(install_repository),
            "script_install_repository": MetadataValue.md(
                f"```shell\n{install_repository['script']}\n```"
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "deadline_script_install_repository": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_script_install_repository",
                ]
            ),
        ),
    },
)
def write_dockerfile_repository(
    context: AssetExecutionContext,
    config_DockerRegistryConfigurableResource: DockerRegistryConfigurableResource,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    deadline_script_install_repository: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        env=env,
    )

    #################################################

    payload = docker_file.parent / "payload"
    payload.mkdir(parents=True, exist_ok=True)

    # @formatter:off
    files_10_2 = {
        # "AWSPortalLink.run": CONFIG.deadline_10_2_installer_aws_portal_link_expanded,
        # "DeadlineClient.run": CONFIG.deadline_10_2_installer_deadline_client_expanded,
        "DeadlineRepository.run": CONFIG.deadline_10_2_installer_deadline_repository_expanded,
    }
    # @formatter:on

    # Copy Deadline Installer(s) to build context
    for key, value in files_10_2.items():
        if not value.exists():
            context.log.error(f"File {value.as_posix()} does not exist")
        context.log.debug(f"{value = }")
        context.log.debug(f"{payload / key = }")
        shutil.copyfile(
            src=value,
            dst=payload / key,
        )

    #################################################

    apt_install_str_deadline_10_2: str = get_apt_install_str(
        apt_install_packages=CONFIG.apt_packages,
    )

    pip_install_str: str = get_pip_install_str(
        pip_install_packages=CONFIG.pip_packages,
        bust_cache=True,
    )

    copy_str: str = get_copy_str(
        temp_dir=payload,
        copy_packages=files_10_2,
        mode=755,
    )

    # @formatter:off
    docker_file_str = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        FROM {parent_image} AS {image_name}
        LABEL authors="{AUTHOR}"

        SHELL ["/bin/bash", "-c"]

        {apt_install_str_deadline_10_2}

        {pip_install_str}

        WORKDIR /installers

        {copy_str}

        WORKDIR /ENTRYPOINT

        COPY --chmod=0755 ./payload/install_repository.sh .

        ENTRYPOINT []
        """).format(
        copy_str=copy_str,
        apt_install_str_deadline_10_2=apt_install_str_deadline_10_2,
        pip_install_str=pip_install_str.format(
            **env,
        ),
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        # Todo: this won't work as expected if len(tags) > 1
        parent_image=f"{build_base_parent_image_prefix}{build_base_parent_image_name}:{build_base_parent_image_tags[0]}",
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    # workspace.yaml
    shutil.copy(
        src=deadline_script_install_repository,
        dst=payload,
    )

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    yield Output(docker_file)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(docker_file),
            docker_file.name: MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "write_dockerfile_repository": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "write_dockerfile_repository"])
        ),
    },
    retry_policy=build_docker_image_retry_policy,
)
def build_docker_image_repository(
    context: AssetExecutionContext,
    config_DockerRegistryConfigurableResource: DockerRegistryConfigurableResource,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    write_dockerfile_repository: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    docker_config_json: pathlib.Path = (
        feature_in.openstudiolandscapes_base.docker_config_json
    )

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        env=env,
    )

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=docker_image,
        docker_config=docker_config,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        docker_config_json=docker_config_json,
        docker_file=write_dockerfile_repository,
    )

    yield Output(image_data)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(image_data),
            "env": MetadataValue.json(env),
            "docker_image": MetadataValue.path(
                f"{image_data['image_prefixes']}{image_data['image_name']}:{image_data['image_tags'][0]}"
            ),
            "docker_cmd": MetadataValue.path(
                get_docker_run_cmd(
                    context=context,
                    image_data=image_data,
                )
            ),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_repository"]),
        ),
        "compose_mongodb_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongodb"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def compose_repository(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
    build: Dict,  # pylint: disable=redefined-outer-name
    compose_mongodb_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[
    Output[MutableMapping[Any, Any]] | AssetMaterialization | Any, None, None
]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{CONFIG.deadline_10_2_repository_install_destination_expanded.as_posix()}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "repository-installer-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                **copy.deepcopy(network_dict),
                **copy.deepcopy(volumes_dict),
                **copy.deepcopy(ports_dict),
                "depends_on": list(compose_mongodb_10_2.get("services", {}).keys()),
                "restart": DockerComposePolicies.RESTART_POLICY.NO.value,
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s"
                % (
                    build["image_prefixes"],
                    build["image_name"],
                    build["image_tags"][0],
                ),
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                "command": ["/ENTRYPOINT/install_repository.sh"],
            },
        },
    }

    if "networks" in compose_networks_10_2:
        network_dict = copy.deepcopy(compose_networks_10_2)
    else:
        network_dict = {}

    docker_chainmap = ChainMap(
        network_dict,
        compose_mongodb_10_2,
        docker_dict,
    )

    docker_chainmap_dict = reduce(deep_merge, docker_chainmap.maps)

    docker_yaml = yaml.dump(docker_chainmap_dict)

    yield Output(docker_chainmap_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_chainmap_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
    description="",
)
def deadline_command_build_docker_image_client(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[List] | AssetMaterialization, None, None]:
    """ """

    # @formatter:off
    deadline_command = [
        "/installers/DeadlineClient.run",
        "--mode",
        "unattended",
        "--prefix",
        "/opt/Thinkbox/Deadline10",
        "--setpermissionsclient",
        "true",
        # "--binariesonly", "true",
        "--repositorydir",
        "/opt/Thinkbox/DeadlineRepository10",
        "--launcherdaemon",
        "false",
        "--httpport",
        str(CONFIG.deadline_10_2_RCS_HTTP_PORT_CONTAINER),
        "--enabletls",
        "false",
        "--proxyalwaysrunning",
        "false",
        "--blockautoupdateoverride",
        "NotBlocked",
        "--webserviceuser",
        "root",
        "--webservice_httpport",
        str(CONFIG.deadline_10_2_WEBSERVICE_HTTP_PORT_CONTAINER),
        "--webservice_enabletls",
        "false",
        # This is new for 10.4:
        # "--remotecontrol", "NotBlocked",
    ]
    # @formatter:on

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "deadline_command_build_client_image_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_build_docker_image_client",
                ]
            ),
        ),
    },
)
def write_dockerfile_client(
    context: AssetExecutionContext,
    config_DockerRegistryConfigurableResource: DockerRegistryConfigurableResource,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    deadline_command_build_client_image_10_2: List,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{dist.name}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        env=env,
    )

    #################################################

    payload = docker_file.parent / "payload"
    payload.mkdir(parents=True, exist_ok=True)

    # @formatter:off
    files_10_2 = {
        # "AWSPortalLink.run": CONFIG.deadline_10_2_installer_aws_portal_link_expanded,
        "DeadlineClient.run": CONFIG.deadline_10_2_installer_deadline_client_expanded,
        # "DeadlineRepository.run": CONFIG.deadline_10_2_installer_deadline_repository_expanded,
    }

    # Copy Deadline Installer(s) to build context
    for key, value in files_10_2.items():
        if not value.exists():
            context.log.error(f"File {value.as_posix()} does not exist")
        context.log.debug(f"{value = }")
        context.log.debug(f"{payload / key = }")
        shutil.copyfile(
            src=value,
            dst=payload / key,
        )
    # @formatter:on

    apt_install_str_deadline_10_2: str = get_apt_install_str(
        apt_install_packages=CONFIG.apt_packages,
    )

    pip_install_str: str = get_pip_install_str(
        pip_install_packages=CONFIG.pip_packages,
        bust_cache=True,
    )

    copy_str: str = get_copy_str(
        temp_dir=payload,
        copy_packages=files_10_2,
        mode=755,
    )

    # @formatter:off
    docker_file_str = textwrap.dedent("""\
        # {auto_generated}
        # {dagster_url}
        
        ################################################################################
        # Multi Stage: Stage 1
        FROM {parent_image} AS base
        LABEL authors="{AUTHOR}"

        SHELL ["/bin/bash", "-c"]

        {apt_install_str_deadline_10_2}

        {pip_install_str}
        
        ################################################################################
        # Multi Stage: Stage 2
        FROM base AS builder

        WORKDIR /installers

        {copy_str}

        RUN {deadline_command}
        
        ################################################################################        
        # Multi Stage: Stage 3
        FROM base AS {image_name}
        
        COPY --from=builder "/opt/Thinkbox" "/opt/Thinkbox"
        
        # https://www.sidefx.com/faq/question/what-are-other-methods-to-tell-the-client-to-look-to-the-license-server/
        # Todo:
        #  - [ ] find a dynamic approach
        RUN echo "serverhost={SESI_LICENSE_SERVER}" > /root/.sesi_licenses.pref

        WORKDIR /opt/Thinkbox

        ENTRYPOINT []
        """).format(
        copy_str=copy_str,
        apt_install_str_deadline_10_2=apt_install_str_deadline_10_2,
        pip_install_str=pip_install_str.format(
            **env,
        ),
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        # Todo: this won't work as expected if len(tags) > 1
        parent_image=f"{build_base_parent_image_prefix}{build_base_parent_image_name}:{build_base_parent_image_tags[0]}",
        deadline_command=" ".join(
            shlex.quote(s) for s in deadline_command_build_client_image_10_2
        ),
        SESI_LICENSE_SERVER="10.1.2.15:1715",
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    yield Output(docker_file)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(docker_file),
            docker_file.name: MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
        },
    )


build_docker_image_client_spec = AssetSpec(
    key=AssetKey(
        [
            *ASSET_HEADER["key_prefix"],
            "build_docker_image_client",
        ]
    ),
    group_name=ASSET_HEADER["group_name"],
    description=textwrap.dedent("""
        Todo
        """),
)


@multi_asset(
    outs={
        "build_docker_image_client": AssetOut.from_spec(build_docker_image_client_spec),
    },
    ins={
        "feature_in": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "feature_in"]),
        ),
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "write_dockerfile_client": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "write_dockerfile_client"])
        ),
    },
    retry_policy=build_docker_image_retry_policy,
)
def build_docker_image_client(
    context: AssetExecutionContext,
    config_DockerRegistryConfigurableResource: DockerRegistryConfigurableResource,
    feature_in: OpenStudioLandscapesFeatureIn,  # pylint: disable=redefined-outer-name
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    write_dockerfile_client: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    docker_config_json: pathlib.Path = (
        feature_in.openstudiolandscapes_base.docker_config_json
    )

    config_engine: ConfigEngine = CONFIG.config_engine

    docker_config: DockerConfigModel = config_engine.openstudiolandscapes__docker_config

    docker_image: Dict = feature_in.openstudiolandscapes_base.docker_image_base

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        env=env,
    )

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=docker_image,
        config_DockerRegistryConfigurableResource=config_DockerRegistryConfigurableResource,
        docker_config=docker_config,
        docker_config_json=docker_config_json,
        docker_file=write_dockerfile_client,
    )

    output_name = "build_docker_image_client"

    yield Output(
        output_name=output_name,
        value=image_data,
    )

    yield AssetMaterialization(
        asset_key=context.asset_key_for_output(output_name),
        metadata={
            "__".join(
                context.asset_key_for_output(output_name).path
            ): MetadataValue.json(image_data),
            "env": MetadataValue.json(env),
            "docker_image": MetadataValue.path(
                f"{image_data['image_prefixes']}{image_data['image_name']}:{image_data['image_tags'][0]}"
            ),
            "docker_cmd": MetadataValue.path(
                get_docker_run_cmd(
                    context=context,
                    image_data=image_data,
                )
            ),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def compose_networks(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[
    Output[Dict[str, Dict[str, Dict[str, str]]]] | AssetMaterialization, None, None
]:

    env: Dict = CONFIG.env

    compose_network_mode = DockerComposePolicies.NETWORK_MODE.BRIDGE

    docker_dict = get_network_dicts(
        context=context,
        compose_network_mode=compose_network_mode,
        env=env,
    )

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_mongo_express(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{CONFIG.deadline_10_2_MONGO_EXPRESS_PORT_HOST}:{CONFIG.deadline_10_2_MONGO_EXPRESS_PORT_CONTAINER}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    service_name = "mongo-express-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    # @formatter:off
    docker_dict = {
        "services": {
            service_name: {
                "image": "docker.io/mongo-express",
                "container_name": container_name,
                "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                "environment": {
                    "TZ": config_engine.tz,
                    "ME_CONFIG_BASICAUTH_USERNAME": CONFIG.deadline_10_2_ME_CONFIG_BASICAUTH_USERNAME,
                    "ME_CONFIG_BASICAUTH_PASSWORD": CONFIG.deadline_10_2_ME_CONFIG_BASICAUTH_PASSWORD,
                    "ME_CONFIG_OPTIONS_EDITORTHEME": CONFIG.deadline_10_2_ME_CONFIG_OPTIONS_EDITORTHEME,
                    "ME_CONFIG_MONGODB_SERVER": CONFIG.deadline_10_2_ME_CONFIG_MONGODB_SERVER,
                    # Todo
                    #  - [ ] no expansion currently happening here
                    "ME_CONFIG_MONGODB_PORT": str(
                        CONFIG.deadline_10_2_ME_CONFIG_MONGODB_PORT
                    ).format(
                        MONGO_DB_PORT_CONTAINER=CONFIG.deadline_10_2_MONGO_DB_PORT_CONTAINER
                    ),
                    "ME_CONFIG_MONGODB_URL": str(
                        CONFIG.deadline_10_2_ME_CONFIG_MONGODB_URL
                    ).format(
                        MONGO_DB_PORT_CONTAINER=CONFIG.deadline_10_2_MONGO_DB_PORT_CONTAINER
                    ),
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                "depends_on": [
                    "mongodb-10-2",
                ],
                **copy.deepcopy(network_dict),
                # Todo
                #  "healthcheck": {
                #      "test": ["CMD", "wget", "-S", f"http://0.0.0.0:{env_10_2.get('MONGO_EXPRESS_PORT_CONTAINER')}"],
                #      "interval": "10s",
                #      "timeout": "2s",
                #      "retries": "3",
                #  },
                **copy.deepcopy(ports_dict),
            },
        },
    }
    # @formatter:on

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```shell\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
    },
)
def script_chown_mongodb(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, str]] | AssetMaterialization, None, None]:

    config_engine: ConfigEngine = CONFIG.config_engine

    ret = dict()

    ret["exe"] = shutil.which("bash")
    ret["script"] = str()

    mongo_db_dir_host = CONFIG.deadline_10_2_database_install_destination_expanded

    # sudo chown 101:65534 DeadlineDatabase10
    # Concept: /usr/bin/sshpass -eENV_VAR /usr/bin/ssh "echo $ENV_VAR | sudo -S <cmd>"
    # Because shutil.chown cannot sudo

    mongo_uid = 101
    mongo_gid = 65534

    # @formatter:off
    ret["script"] += "#!/bin/bash\n"
    ret["script"] += "\n"
    # ret["script"] += f"{shutil.which('sshpass')} -eSSH_PASS ssh {env_10_2['SSH_USER']}@{env_10_2['SSH_HOST']} \"echo $SSH_PASS | sudo -S chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()}\"\n"

    match config_engine.sudo_method:
        # Todo:
        #  - [ ] implement `su` command variance
        #  - [ ] askpass: alternative to "echo SUDO_PASS | sudo --stdin"
        # case SudoMethod.SU:
        #     ret[
        #         "script"
        #     ] += f"echo $SUDO_PASS | {CONFIG.sudo_method.value} -S -k /usr/bin/chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()};\n"
        case SudoMethod.SUDO:
            ret[
                "script"
            ] += f"echo ${{SUDO_PASS}} | {config_engine.sudo_method.value} --stdin --reset-timestamp /usr/bin/chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()};\n"
        case SudoMethod.PKEXEC:
            ret[
                "script"
            ] += f"{config_engine.sudo_method.value} /usr/bin/chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()};\n"

    ret["script"] += "\n"
    ret["script"] += "echo Success;\n"
    ret["script"] += "exit 0;\n"
    # @formatter:on

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
            "script_chown": MetadataValue.md(f"```shell\n{ret['script']}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "script_chown_mongodb_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "script_chown_mongodb"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_mongodb(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    script_chown_mongodb_10_2: Dict[str, str],  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{CONFIG.deadline_10_2_MONGO_DB_PORT_HOST}:{CONFIG.deadline_10_2_MONGO_DB_PORT_CONTAINER}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    # image = "docker.io/mongodb/mongodb-community-server:4.4-ubuntu2004"

    # cmd_docker_run = [
    #     shutil.which("docker"),
    #     "run",
    #     "--rm",
    #     "--interactive",
    #     "--tty",
    #     image,
    #     "/bin/bash",
    # ]

    volumes_dict = {"volumes": []}

    mongo_db_dir_host = CONFIG.deadline_10_2_database_install_destination_expanded
    mongo_db_dir_host.mkdir(parents=True, exist_ok=True)

    stdout_stderr = {
        "stdout": MetadataValue.md(f"```shell\nNone\n```"),
        "stderr": MetadataValue.md(f"```shell\nNone\n```"),
    }

    if not CONFIG.deadline_10_2_MONGODB_INSIDE_CONTAINER:

        if bool(script_chown_mongodb_10_2["script"]):

            context.log.info(f"Setting ownership of {mongo_db_dir_host.as_posix()}...")

            if config_engine.sudo_method == SudoMethod.SUDO:
                # Todo
                #  - [ ] Choose EnvVar or os.environ for SUDO_PASS
                sudo_pass = EnvVar("SUDO_PASS").get_value() or os.environ.get(
                    "SUDO_PASS", None
                )
                if sudo_pass is None:
                    raise ValueError(
                        "Environment variable `SUDO_PASS` is not set but required "
                        f"with `sudo_method` = {config_engine.sudo_method}"
                    )
                env_proc = {
                    "SUDO_PASS": sudo_pass,
                }
            else:
                env_proc = {}

            proc = subprocess.Popen(
                script_chown_mongodb_10_2["exe"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                stdin=subprocess.PIPE,
                env=env_proc,
            )

            stdout, stderr = proc.communicate(
                input=script_chown_mongodb_10_2["script"].encode(),
            )

            stdout_stderr = {
                "stdout": MetadataValue.md(
                    f"```shell\n{stdout.decode(encoding='utf-8')}\n```"
                ),
                "stderr": MetadataValue.md(
                    f"```shell\n{stderr.decode(encoding='utf-8')}\n```"
                ),
            }

            # helpers.iterate_fds(
            #     (
            #         proc.stderr,
            #         proc.stdout,
            #     ),
            #     (
            #         context.log.warning,
            #         context.log.info,
            #     )
            # )

        volumes_dict["volumes"].insert(
            0,
            f"{mongo_db_dir_host.as_posix()}:{CONFIG.deadline_10_2_DEFAULT_DBPATH_CONTAINER.as_posix()}:rw",  # Todo: revise this
        )

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "mongodb-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    docker_dict = {
        "services": {
            service_name: {
                "image": CONFIG.deadline_10_2_mongodb_docker_image,
                "container_name": container_name,
                "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                "command": [
                    "--port",
                    str(CONFIG.deadline_10_2_MONGO_DB_PORT_CONTAINER),
                    "--dbpath",
                    CONFIG.deadline_10_2_DEFAULT_DBPATH_CONTAINER.as_posix(),
                    "--bind_ip_all",
                    "--noauth",
                    "--storageEngine",
                    "wiredTiger",
                    "--tlsMode",
                    "disabled",
                ],
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
            **stdout_stderr,
        },
    )


@asset(
    **ASSET_HEADER,
    ins={},
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_rcs_runner(
    context: AssetExecutionContext,
) -> Generator[Output[List[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinercs",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "deadline_command_compose_rcs_runner_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_compose_rcs_runner",
                ]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_rcs_runner(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    build: Dict,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_rcs_runner_10_2: List,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{CONFIG.deadline_10_2_RCS_HTTP_PORT_HOST}:{CONFIG.deadline_10_2_RCS_HTTP_PORT_CONTAINER}",
                # Todo:
                #  - [ ] Expose OpenStudioLandscapes standard Ports (https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/considerations.html#firewall-anti-virus-security-considerations)
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{CONFIG.deadline_10_2_repository_work_dir_expanded.as_posix()}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "deadline-rcs-runner-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s"
                % (
                    build["image_prefixes"],
                    build["image_name"],
                    build["image_tags"][0],
                ),
                "depends_on": {
                    "repository-installer-10-2": {
                        "condition": "service_completed_successfully",
                    },
                },
                "command": deadline_command_compose_rcs_runner_10_2,
                "healthcheck": {
                    "test": [
                        "CMD",
                        "curl",
                        "-f",
                        f"http://localhost:{CONFIG.deadline_10_2_RCS_HTTP_PORT_CONTAINER}",
                    ],
                    "interval": "10s",
                    "timeout": "2s",
                    "retries": "3",
                },
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


deadline_command_compose_pulse_runner_spec = AssetSpec(
    key=AssetKey(
        [
            *ASSET_HEADER["key_prefix"],
            "deadline_command_compose_pulse_runner",
        ]
    ),
    group_name=ASSET_HEADER["group_name"],
    description=textwrap.dedent("""
        This executes the OpenStudioLandscapes Repository Installer. Needs to be done only once.
        """),
)


@multi_asset(
    outs={
        "deadline_command_compose_pulse_runner": AssetOut.from_spec(
            deadline_command_compose_pulse_runner_spec
        ),
    },
    ins={},
)
def deadline_command_compose_pulse_runner(
    context: AssetExecutionContext,
) -> Generator[Output[List[str]] | AssetMaterialization, None, None]:

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinepulse",
        "-nogui",
        "-nosplash",
    ]

    output_name = "deadline_command_compose_pulse_runner"

    yield Output(
        output_name=output_name,
        value=deadline_command,
    )

    yield AssetMaterialization(
        asset_key=context.asset_key_for_output(output_name),
        metadata={
            "__".join(
                context.asset_key_for_output(output_name).path
            ): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


compose_pulse_runner_spec = AssetSpec(
    key=AssetKey(
        [
            *ASSET_HEADER["key_prefix"],
            "compose_pulse_runner",
        ]
    ),
    group_name=ASSET_HEADER["group_name"],
    description=textwrap.dedent("""
        Todo
        """),
)


@multi_asset(
    outs={
        "compose_pulse_runner": AssetOut.from_spec(compose_pulse_runner_spec),
    },
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_pulse_runner_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_compose_pulse_runner",
                ]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_pulse_runner(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    build: Dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_pulse_runner_10_2: List,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{CONFIG.deadline_10_2_repository_work_dir_expanded.as_posix()}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "deadline-pulse-runner-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    if CONFIG.deadline_10_2_DISABLE_LOCAL_PULSE:

        docker_dict = {}

    else:

        docker_dict = {
            "services": {
                service_name: {
                    "container_name": container_name,
                    "hostname": host_name,
                    "domainname": config_engine.openstudiolandscapes__domain_lan,
                    "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                    # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                    # % (build["image_name"], build["image_tags"][0]),
                    "image": "%s%s:%s"
                    % (
                        build["image_prefixes"],
                        build["image_name"],
                        build["image_tags"][0],
                    ),
                    "depends_on": {
                        "deadline-rcs-runner-10-2": {
                            "condition": "service_started",
                        },
                    },
                    "environment": {
                        "TZ": config_engine.tz,
                        **config_engine.global_environment_variables,
                        **CONFIG.local_environment_variables,
                    },
                    **copy.deepcopy(network_dict),
                    **copy.deepcopy(volumes_dict),
                    **copy.deepcopy(ports_dict),
                    "command": deadline_command_compose_pulse_runner_10_2,
                },
            },
        }

    docker_yaml = yaml.dump(docker_dict)

    output_name = "compose_pulse_runner"

    yield Output(
        output_name=output_name,
        value=docker_dict,
    )

    yield AssetMaterialization(
        asset_key=context.asset_key_for_output(output_name),
        metadata={
            "__".join(
                context.asset_key_for_output(output_name).path
            ): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


deadline_command_compose_worker_runner_spec = AssetSpec(
    key=AssetKey(
        [
            *ASSET_HEADER["key_prefix"],
            "deadline_command_compose_worker_runner",
        ]
    ),
    group_name=ASSET_HEADER["group_name"],
    description=textwrap.dedent("""
        This executes the OpenStudioLandscapes Repository Installer. Needs to be done only once.
        """),
)


@multi_asset(
    outs={
        "deadline_command_compose_worker_runner": AssetOut.from_spec(
            deadline_command_compose_worker_runner_spec
        ),
    },
    ins={},
)
def deadline_command_compose_worker_runner(
    context: AssetExecutionContext,
) -> Generator[Output[List[str]] | AssetMaterialization, None, None]:

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlineworker",
        "-nogui",
        "-nosplash",
    ]

    output_name = "deadline_command_compose_worker_runner"

    yield Output(
        output_name=output_name,
        value=deadline_command,
    )

    yield AssetMaterialization(
        asset_key=context.asset_key_for_output(output_name),
        metadata={
            "__".join(
                context.asset_key_for_output(output_name).path
            ): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_worker_runner_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_compose_worker_runner",
                ]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_worker_runner(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    build: Dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_worker_runner_10_2: List,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{CONFIG.deadline_10_2_repository_work_dir_expanded.as_posix()}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    service_name = "deadline-worker-runner-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    if CONFIG.deadline_10_2_DISABLE_LOCAL_WORKER:

        docker_dict = {}

    else:

        docker_dict = {
            "services": {
                service_name: {
                    "container_name": container_name,
                    "hostname": host_name,
                    "domainname": config_engine.openstudiolandscapes__domain_lan,
                    "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                    # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                    # % (build["image_name"], build["image_tags"][0]),
                    "image": "%s%s:%s"
                    % (
                        build["image_prefixes"],
                        build["image_name"],
                        build["image_tags"][0],
                    ),
                    "depends_on": {
                        "deadline-rcs-runner-10-2": {
                            "condition": "service_started",
                        },
                    },
                    "environment": {
                        "TZ": config_engine.tz,
                        **config_engine.global_environment_variables,
                        **CONFIG.local_environment_variables,
                    },
                    **copy.deepcopy(network_dict),
                    **copy.deepcopy(volumes_dict),
                    **copy.deepcopy(ports_dict),
                    "command": deadline_command_compose_worker_runner_10_2,
                },
            },
        }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={},
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_webservice_runner(
    context: AssetExecutionContext,
) -> Generator[Output[List[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinewebservice",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "CONFIG": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "CONFIG"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_webservice_runner_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_compose_webservice_runner",
                ]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_webservice_runner(
    context: AssetExecutionContext,
    CONFIG: config.models.Config,  # pylint: disable=redefined-outer-name
    build: Dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_webservice_runner_10_2: List,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: Dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[Dict[str, Dict[str, Dict]]] | AssetMaterialization, None, None]:
    """ """

    env: Dict = CONFIG.env

    config_engine: ConfigEngine = CONFIG.config_engine

    # network_dict = {}
    # ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{CONFIG.deadline_10_2_WEBSERVICE_HTTP_PORT_HOST}:{CONFIG.deadline_10_2_WEBSERVICE_HTTP_PORT_CONTAINER}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}
        ports_dict = {}
    else:
        network_dict = {}
        ports_dict = {}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{CONFIG.deadline_10_2_repository_work_dir_expanded.as_posix()}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=CONFIG.docker_compose_expanded,
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": list(
            {
                *_volume_relative,
                *config_engine.global_bind_volumes,
                *CONFIG.local_bind_volumes,
            }
        )
    }

    service_name = "deadline-webservice-runner-10-2"
    container_name, host_name = get_docker_compose_names(
        context=context,
        service_name=service_name,
        landscape_id=env.get("LANDSCAPE", "default"),
        domain_lan=config_engine.openstudiolandscapes__domain_lan,
    )
    # container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    # host_name = ".".join(
    #     [
    #         service_name,
    #         env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
    #     ]
    # )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": config_engine.openstudiolandscapes__domain_lan,
                "restart": DockerComposePolicies.RESTART_POLICY.ALWAYS.value,
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s"
                % (
                    build["image_prefixes"],
                    build["image_name"],
                    build["image_tags"][0],
                ),
                "depends_on": {
                    "deadline-rcs-runner-10-2": {
                        "condition": "service_started",
                    },
                },
                "healthcheck": {
                    "test": [
                        "CMD",
                        "curl",
                        "-f",
                        f"http://localhost:{CONFIG.deadline_10_2_WEBSERVICE_HTTP_PORT_CONTAINER}",
                    ],
                    "interval": "10s",
                    "timeout": "2s",
                    "retries": "3",
                },
                "environment": {
                    "TZ": config_engine.tz,
                    **config_engine.global_environment_variables,
                    **CONFIG.local_environment_variables,
                },
                **copy.deepcopy(network_dict),
                "command": deadline_command_compose_webservice_runner_10_2,
                **copy.deepcopy(volumes_dict),
                **copy.deepcopy(ports_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "compose_webservice_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_webservice_runner"]),
        ),
        "compose_worker_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_worker_runner"]),
        ),
        "compose_pulse_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_pulse_runner"]),
        ),
        "compose_rcs_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_rcs_runner"]),
        ),
        "compose_mongo_express": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongo_express"]),
        ),
        "compose_mongodb": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongodb"]),
        ),
        "compose_repository": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_repository"]),
        ),
    },
)
def compose_maps(
    context: AssetExecutionContext,
    **kwargs,  # pylint: disable=redefined-outer-name
) -> Generator[Output[List[Dict]] | AssetMaterialization, None, None]:

    ret = list(kwargs.values())

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
        },
    )
