import copy
import json
import pathlib
import shlex
import shutil
import subprocess
import textwrap
import urllib.parse
from collections import ChainMap
from functools import reduce
from typing import Any, Generator, MutableMapping

import yaml
from dagster import (
    AssetExecutionContext,
    AssetIn,
    AssetKey,
    AssetMaterialization,
    EnvVar,
    MetadataValue,
    Output,
    asset,
)
from docker_compose_graph.utils import *
from OpenStudioLandscapes.engine.common_assets.compose import get_compose
from OpenStudioLandscapes.engine.common_assets.constants import get_constants
from OpenStudioLandscapes.engine.common_assets.docker_compose_graph import (
    get_docker_compose_graph,
)
from OpenStudioLandscapes.engine.common_assets.docker_config import get_docker_config
from OpenStudioLandscapes.engine.common_assets.docker_config_json import (
    get_docker_config_json,
)
from OpenStudioLandscapes.engine.common_assets.env import get_env
from OpenStudioLandscapes.engine.common_assets.feature_out import get_feature_out
from OpenStudioLandscapes.engine.common_assets.group_in import get_group_in
from OpenStudioLandscapes.engine.common_assets.group_out import get_group_out
from OpenStudioLandscapes.engine.constants import *
from OpenStudioLandscapes.engine.enums import *
from OpenStudioLandscapes.engine.utils import *

from OpenStudioLandscapes.Deadline_10_2.constants import *

constants = get_constants(
    ASSET_HEADER=ASSET_HEADER,
)


docker_config = get_docker_config(
    ASSET_HEADER=ASSET_HEADER,
)


group_in = get_group_in(
    ASSET_HEADER=ASSET_HEADER,
    ASSET_HEADER_PARENT=ASSET_HEADER_BASE,
    input_name=str(GroupIn.BASE_IN),
)


env = get_env(
    ASSET_HEADER=ASSET_HEADER,
)


group_out = get_group_out(
    ASSET_HEADER=ASSET_HEADER,
)


docker_compose_graph = get_docker_compose_graph(
    ASSET_HEADER=ASSET_HEADER,
)


compose = get_compose(
    ASSET_HEADER=ASSET_HEADER,
)


feature_out = get_feature_out(
    ASSET_HEADER=ASSET_HEADER,
    feature_out_ins={
        "env": dict,
        "compose": dict,
        "group_in": dict,
        "deadline_command_compose_worker_runner": list,
        "deadline_command_compose_pulse_runner": list,
        "compose_rcs_runner": dict,
    },
)


docker_config_json = get_docker_config_json(
    ASSET_HEADER=ASSET_HEADER,
)


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
)
def connection_ini(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    # @formatter:off
    connection_ini = textwrap.dedent(
        """\
        # {auto_generated}
        # {dagster_url}
        [Connection]
        AlternatePort=0
        Authenticate=False
        DatabaseName={MONGO_DB_NAME}
        DbType=MongoDB
        EnableSSL=False
        Hostname={MONGO_DB_HOST}
        PasswordHash=
        Port={MONGO_DB_PORT_CONTAINER}
        ReplicaSetName=
        SplitDB=False
        Username=
        Version=10
        StorageAccess=Database
        CACertificatePath=
        ClientsThatPreferSecondaryReplicas=
        """
    ).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        **env,
    )
    # @formatter:on

    deadline_connection_ini = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "configs",
        "DeadlineRepository10",
        "settings",
        "connection.ini",
    ).expanduser()

    deadline_connection_ini.parent.mkdir(parents=True, exist_ok=True)

    with open(deadline_connection_ini, "w") as fw:
        fw.write(connection_ini)

    yield Output(deadline_connection_ini)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(
                deadline_connection_ini
            ),
            "connection_ini": MetadataValue.md(f"```\n{connection_ini}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
)
def deadline_ini(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    # @formatter:off
    deadline_ini = textwrap.dedent(
        """\
        # {auto_generated}
        # {dagster_url}
        # Full Documentation
        # https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/client-config.html#client-config-conn-server-ref-label
        [Deadline]
        # # For Remote
        # ConnectionType=Remote
        # ProxyRoot=deadline-rcs-runner-10-2.{OPENSTUDIOLANDSCAPES__DOMAIN_LAN}:8888
        # ProxyRoot0=deadline-rcs-runner-10-2.{OPENSTUDIOLANDSCAPES__DOMAIN_LAN}:8888
        # ###
        # #################################
        # For Repository
        ConnectionType=Repository
        NetworkRoot=/opt/Thinkbox/DeadlineRepository10
        NetworkRoot0=/opt/Thinkbox/DeadlineRepository10
        ###
        WebServiceHttpListenPort={WEBSERVICE_HTTP_PORT_CONTAINER}
        WebServiceTlsListenPort=0
        WebServiceTlsServerCert=
        WebServiceTlsCaCert=
        WebServiceTlsAuth=False
        WebServiceClientSSLAuthentication=NotRequired
        HttpListenPort={RCS_HTTP_PORT_CONTAINER}
        TlsListenPort=0
        LicenseMode=LicenseFree
        Region=
        LauncherListeningPort=17000
        LauncherServiceStartupDelay=60
        AutoConfigurationPort=17001
        SlaveStartupPort=17003
        LicenseForwarderListeningPort=17004
        SlaveDataRoot=
        NoGuiMode=false
        AutoUpdateOverride=false
        IncludeRCSInLauncherMenu=true
        DbSSLCertificate=
        AutoUpdateBlock=NotBlocked

        # Controlled by Docker
        LaunchRemoteConnectionServerAtStartup=false
        KeepRemoteConnectionServerRunning=false
        LaunchPulseAtStartup=false
        KeepPulseRunning=false
        LaunchBalancerAtStartup=false
        KeepBalancerRunning=false
        KeepWebServiceRunning=false
        KeepWorkerRunning=false
        RestartStalledSlave=false
        LaunchLicenseForwarderAtStartup=false
        KeepLicenseForwarderRunning=false
        LaunchSlaveAtStartup=false
        """
    ).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        **env,
    )
    # @formatter:on

    # deadline_client_ini = pathlib.Path(
    #     env_10_2.get(f"DEADLINE_CLIENT_DEADLINE_INI_{'__'.join(ASSET_HEADER["key_prefix"])}")
    # )

    deadline_client_ini = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "configs",
        "Deadline10",
        "deadline.ini",
    ).expanduser()

    deadline_client_ini.parent.mkdir(parents=True, exist_ok=True)

    with open(deadline_client_ini, "w") as fw:
        fw.write(deadline_ini)

    yield Output(deadline_client_ini)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(deadline_client_ini),
            "connection_ini": MetadataValue.md(f"```\n{deadline_ini}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
)
def pip_packages(
    context: AssetExecutionContext,
) -> Generator[Output[list] | AssetMaterialization, None, None]:
    """ """

    _pip_packages: list = [
        # Todo:
        #  - [ ] (LOW) OpenStudioLandscapes SSL authentication
        # "git+https://github.com/michimussato/SSLGeneration.git@packaging",
    ]

    yield Output(_pip_packages)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(_pip_packages),
        },
    )


@asset(
    **ASSET_HEADER,
)
def apt_packages(
    context: AssetExecutionContext,
) -> Generator[Output[dict] | AssetMaterialization, None, None]:
    """ """

    _apt_packages = {}

    _apt_packages["deadline_10_2"] = [
        "bzip2",  # https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/system-requirements.html#system-requirements-linux-ref-label
        # this was an attempt to set the hostname with hostnamectl dynamically
        # however, systemd should not run inside a container (which makes sense):
        # https://stackoverflow.com/questions/59466250/docker-system-has-not-been-booted-with-systemd-as-init-system
        # "systemd",
    ]

    yield Output(_apt_packages)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(_apt_packages),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "docker_config_json": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config_json"]),
        ),
        "group_in": AssetIn(
            AssetKey([*ASSET_HEADER_BASE["key_prefix"], str(GroupIn.BASE_IN)])
        ),
        "docker_config": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config"])
        ),
        "apt_packages": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "apt_packages"]),
        ),
        "pip_packages": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "pip_packages"]),
        ),
    },
)
def build_docker_image(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    docker_config_json: pathlib.Path,  # pylint: disable=redefined-outer-name
    group_in: dict,  # pylint: disable=redefined-outer-name
    docker_config: DockerConfig,  # pylint: disable=redefined-outer-name
    apt_packages: dict[str, list[str]],  # pylint: disable=redefined-outer-name
    pip_packages: list,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict] | AssetMaterialization, None, None]:
    """ """

    docker_image: dict = group_in["docker_image"]

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=docker_image,
        docker_config=docker_config,
        env=env,
    )

    #################################################

    # @formatter:off
    files_10_2 = {
        "AWSPortalLink.run": env["INSTALLER_AWSPortalLink"],
        "DeadlineClient.run": env["INSTALLER_DeadlineClient"],
        "DeadlineRepository.run": env["INSTALLER_DeadlineRepository"],
    }
    # @formatter:on

    apt_install_str_deadline_10_2: str = get_apt_install_str(
        apt_install_packages=apt_packages["deadline_10_2"],
    )

    pip_install_str: str = get_pip_install_str(pip_install_packages=pip_packages)

    docker_payload = ".payload"
    tmpdir = docker_file.parent / docker_payload
    tmpdir.mkdir(exist_ok=True, parents=True)

    copy_str: str = get_copy_str(
        temp_dir=tmpdir,
        copy_packages=files_10_2,
        mode=755,
    )

    # @formatter:off
    docker_file_str = textwrap.dedent(
        """\
        # {auto_generated}
        # {dagster_url}
        FROM {parent_image} AS {image_name}
        LABEL authors="{AUTHOR}"

        SHELL ["/bin/bash", "-c"]

        RUN apt-get update && apt-get upgrade -y

        {apt_install_str_deadline_10_2}

        {pip_install_str}

        WORKDIR /installers

        {copy_str}

        # Todo:
        # RUN thinkbox-ssl-gen --help

        RUN apt-get clean

        ENTRYPOINT []
        """
    ).format(
        copy_str=copy_str,
        apt_install_str_deadline_10_2=apt_install_str_deadline_10_2,
        pip_install_str=pip_install_str.format(
            **env,
        ),
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        # Todo: this won't work as expected if len(tags) > 1
        parent_image=f"{build_base_parent_image_prefix}{build_base_parent_image_name}:{build_base_parent_image_tags[0]}",
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    for key, value in files_10_2.items():
        if not pathlib.Path(value).exists():
            context.log.error(f"File {value} does not exist")
        context.log.debug(f"{value = }")
        context.log.debug(f"{pathlib.Path(tmpdir) / key = }")
        shutil.copyfile(
            src=value,
            dst=pathlib.Path(tmpdir) / key,
        )

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=docker_image,
        docker_config=docker_config,
        docker_config_json=docker_config_json,
        docker_file=docker_file,
    )

    yield Output(image_data)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(image_data),
            "docker_file": MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_install_repository(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list] | AssetMaterialization, None, None]:
    """ """

    # Todo
    #  - [ ] skip installation if already installed

    deadline_command = [
        "/installers/DeadlineRepository.run",
        "--mode",
        "unattended",
        "--prefix",
        "/opt/Thinkbox/DeadlineRepository10",
        "--setpermissions",
        "true",
        "--dbtype",
        "MongoDB",
        "--installmongodb",
        "false",
        "--dbhost",
        env["MONGO_DB_HOST"],
        "--dbport",
        env["MONGO_DB_PORT_HOST"],
        "--dbname",
        env["MONGO_DB_NAME"],
        "--dbauth",
        "false",
        "--dbssl",
        "false",
        "--installSecretsManagement",
        "false",
        "--importrepositorysettings",
        "false",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "deadline_command_install_repository": AssetIn(
            AssetKey(
                [*ASSET_HEADER["key_prefix"], "deadline_command_install_repository"]
            ),
        ),
    },
)
def deadline_script_install_repository(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    deadline_command_install_repository: list,  # pylint: disable=redefined-outer-name
) -> Generator[Output[pathlib.Path] | AssetMaterialization, None, None]:
    """ """

    install_repository = dict()

    install_repository["exe"] = shutil.which("bash")
    install_repository["script"] = str()

    # https://github.com/michimussato/kitsu-setup/blob/main/README_KITSU.md
    install_repository["script"] += "#!/bin/bash\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += "if [[ ! -z \"$( ls -A '/opt/Thinkbox/DeadlineRepository10')\" ]]; then\n"
    install_repository[
        "script"
    ] += "    echo /opt/Thinkbox/DeadlineRepository10 is not empty.\n"
    install_repository["script"] += "    echo Using existing Installation.\n"
    install_repository["script"] += "    echo Quit.\n"
    install_repository["script"] += "    exit 0;\n"
    install_repository["script"] += "fi\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += "echo /opt/Thinkbox/DeadlineRepository10 is empty or does not exist.\n"
    install_repository["script"] += "echo Installing Repository...\n"
    install_repository["script"] += "\n"
    install_repository[
        "script"
    ] += f"{shlex.join(deadline_command_install_repository)}\n"
    install_repository["script"] += "\n"
    install_repository["script"] += "echo Repository installed.\n"
    install_repository["script"] += "\n"
    install_repository["script"] += "exit 0\n"

    install_repository_script = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "__".join(context.asset_key.path),
        "install_repository.sh",
    )

    install_repository_script.parent.mkdir(parents=True, exist_ok=True)

    with open(
        file=install_repository_script,
        mode="w",
    ) as sh_install_repository:
        sh_install_repository.write(install_repository["script"])

    yield Output(install_repository_script)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.path(
                install_repository_script
            ),
            "dict_install_repository": MetadataValue.json(install_repository),
            "script_install_repository": MetadataValue.md(
                f"```shell\n{install_repository['script']}\n```"
            ),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "docker_config_json": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config_json"]),
        ),
        "docker_config": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config"])
        ),
        # "group_in": AssetIn(
        #     AssetKey([*ASSET_HEADER_BASE["key_prefix"], str(GroupIn.BASE_IN)])
        # ),
        "build_docker_image_stem": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image"]),
        ),
        "deadline_script_install_repository": AssetIn(
            AssetKey(
                [*ASSET_HEADER["key_prefix"], "deadline_script_install_repository"]
            ),
        ),
    },
)
def build_docker_image_repository(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    docker_config_json: pathlib.Path,  # pylint: disable=redefined-outer-name
    docker_config: DockerConfig,  # pylint: disable=redefined-outer-name
    # group_in: dict,  # pylint: disable=redefined-outer-name
    build_docker_image_stem: dict,  # pylint: disable=redefined-outer-name
    deadline_script_install_repository: pathlib.Path,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict] | AssetMaterialization, None, None]:
    """ """

    # docker_image: dict = build_docker_image_stem

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=build_docker_image_stem,
        docker_config=docker_config,
        env=env,
    )

    #################################################

    # @formatter:off
    docker_file_str = textwrap.dedent(
        """\
        # {auto_generated}
        # {dagster_url}
        FROM {parent_image} AS {image_name}
        LABEL authors="{AUTHOR}"

        SHELL ["/bin/bash", "-c"]

        WORKDIR /ENTRYPOINT

        COPY --chmod=0755 ./payload/install_repository.sh .

        ENTRYPOINT []
        """
    ).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        # Todo: this won't work as expected if len(tags) > 1
        parent_image=f"{build_base_parent_image_prefix}{build_base_parent_image_name}:{build_base_parent_image_tags[0]}",
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    payload = docker_file.parent / "payload"
    payload.mkdir(parents=True, exist_ok=True)

    # workspace.yaml
    shutil.copy(
        src=deadline_script_install_repository,
        dst=payload,
    )

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=build_docker_image_stem,
        docker_config=docker_config,
        docker_config_json=docker_config_json,
        docker_file=docker_file,
    )

    yield Output(image_data)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(image_data),
            "docker_file": MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_repository"]),
        ),
        "compose_mongodb_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongodb"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def compose_repository(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
    build: dict,  # pylint: disable=redefined-outer-name
    compose_mongodb_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[MutableMapping] | AssetMaterialization, None, None]:
    """ """

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{env['REPOSITORY_INSTALL_DESTINATION_%s' % '__'.join(ASSET_HEADER['key_prefix'])]}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=pathlib.Path(env["DOCKER_COMPOSE"]),
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
        ]
    }

    service_name = "repository-installer-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_REPOSITORY"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                **copy.deepcopy(network_dict),
                **copy.deepcopy(volumes_dict),
                **copy.deepcopy(ports_dict),
                "depends_on": list(compose_mongodb_10_2.get("services", {}).keys()),
                "restart": "no",
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s" % (build["image_prefixes"], build["image_name"], build["image_tags"][0]),
                "command": ["/ENTRYPOINT/install_repository.sh"],
            },
        },
    }

    if "networks" in compose_networks_10_2:
        network_dict = copy.deepcopy(compose_networks_10_2)
    else:
        network_dict = {}

    docker_chainmap = ChainMap(
        network_dict,
        compose_mongodb_10_2,
        docker_dict,
    )

    docker_chainmap_dict = reduce(deep_merge, docker_chainmap.maps)

    docker_yaml = yaml.dump(docker_chainmap_dict)

    yield Output(docker_chainmap_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_chainmap_dict),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="",
)
def deadline_command_build_docker_image_client(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list] | AssetMaterialization, None, None]:
    """ """

    # @formatter:off
    deadline_command = [
        "/installers/DeadlineClient.run",
        "--mode",
        "unattended",
        "--prefix",
        "/opt/Thinkbox/Deadline10",
        "--setpermissionsclient",
        "true",
        # "--binariesonly", "true",
        "--repositorydir",
        "/opt/Thinkbox/DeadlineRepository10",
        "--launcherdaemon",
        "false",
        "--httpport",
        env["RCS_HTTP_PORT_CONTAINER"],
        "--enabletls",
        "false",
        "--proxyalwaysrunning",
        "false",
        "--blockautoupdateoverride",
        "NotBlocked",
        "--webserviceuser",
        "root",
        "--webservice_httpport",
        env["WEBSERVICE_HTTP_PORT_CONTAINER"],
        "--webservice_enabletls",
        "false",
        # This is new for 10.4:
        # "--remotecontrol", "NotBlocked",
    ]
    # @formatter:on

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "docker_config_json": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config_json"]),
        ),
        "docker_config": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "docker_config"])
        ),
        # "group_in": AssetIn(
        #     AssetKey([*ASSET_HEADER_BASE["key_prefix"], str(GroupIn.BASE_IN)])
        # ),
        "build_docker_image_stem": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image"]),
        ),
        "deadline_command_build_client_image_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_build_docker_image_client",
                ]
            ),
        ),
    },
)
def build_docker_image_client(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    docker_config_json: pathlib.Path,  # pylint: disable=redefined-outer-name
    docker_config: DockerConfig,  # pylint: disable=redefined-outer-name
    # group_in: dict,  # pylint: disable=redefined-outer-name
    build_docker_image_stem: dict,  # pylint: disable=redefined-outer-name
    deadline_command_build_client_image_10_2: list,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict] | AssetMaterialization, None, None]:
    """ """

    # docker_image: dict = group_in["docker_image"]

    docker_file = pathlib.Path(
        env["DOT_LANDSCAPES"],
        env.get("LANDSCAPE", "default"),
        f"{ASSET_HEADER['group_name']}__{'__'.join(ASSET_HEADER['key_prefix'])}",
        "__".join(context.asset_key.path),
        "Dockerfiles",
        "Dockerfile",
    )

    docker_file.parent.mkdir(parents=True, exist_ok=True)

    #################################################

    (
        image_name,
        image_prefixes,
        tags,
        build_base_parent_image_prefix,
        build_base_parent_image_name,
        build_base_parent_image_tags,
    ) = get_image_metadata(
        context=context,
        docker_image=build_docker_image_stem,
        docker_config=docker_config,
        env=env,
    )

    #################################################

    # @formatter:off
    docker_file_str = textwrap.dedent(
        """\
        # {auto_generated}
        # {dagster_url}
        FROM {parent_image} AS {image_name}
        LABEL authors="{AUTHOR}"

        SHELL ["/bin/bash", "-c"]

        WORKDIR /installers

        RUN {deadline_command}

        WORKDIR /opt/Thinkbox

        ENTRYPOINT []
        """
    ).format(
        auto_generated=f"AUTO-GENERATED by Dagster Asset {'__'.join(context.asset_key.path)}",
        dagster_url=urllib.parse.quote(
            f"http://localhost:3000/asset-groups/{'%2F'.join(context.asset_key.path)}",
            safe=":/%",
        ),
        image_name=image_name,
        # Todo: this won't work as expected if len(tags) > 1
        parent_image=f"{build_base_parent_image_prefix}{build_base_parent_image_name}:{build_base_parent_image_tags[0]}",
        deadline_command=" ".join(
            shlex.quote(s) for s in deadline_command_build_client_image_10_2
        ),
        **env,
    )
    # @formatter:on

    with open(docker_file, "w") as fw:
        fw.write(docker_file_str)

    with open(docker_file, "r") as fr:
        docker_file_content = fr.read()

    #################################################

    image_data, logs = create_image(
        context=context,
        image_name=image_name,
        image_prefixes=image_prefixes,
        tags=tags,
        docker_image=build_docker_image_stem,
        docker_config=docker_config,
        docker_config_json=docker_config_json,
        docker_file=docker_file,
    )

    yield Output(image_data)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(image_data),
            "docker_file": MetadataValue.md(f"```shell\n{docker_file_content}\n```"),
            "env": MetadataValue.json(env),
            "logs": MetadataValue.json(logs),
        },
    )


@asset(
    **ASSET_HEADER,
)
def compose_networks(
    context: AssetExecutionContext,
) -> Generator[
    Output[dict[str, dict[str, dict[str, str]]]] | AssetMaterialization, None, None
]:

    compose_network_mode = ComposeNetworkMode.DEFAULT

    if compose_network_mode == ComposeNetworkMode.DEFAULT:
        docker_dict = {
            "networks": {
                "mongodb": {
                    "name": "network_mongodb-10-2",
                },
                "repository": {
                    "name": "network_repository-10-2",
                },
                "ayon": {
                    "name": "network_ayon-10-2",
                },
            },
        }

    else:
        docker_dict = {
            "network_mode": compose_network_mode.value,
        }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```shell\n{docker_yaml}\n```"),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_mongo_express(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{env['MONGO_EXPRESS_PORT_HOST']}:{env['MONGO_EXPRESS_PORT_CONTAINER']}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    service_name = "mongo-express-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_MONGO_EXPRESS"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    # @formatter:off
    docker_dict = {
        "services": {
            service_name: {
                "image": "docker.io/mongo-express",
                "container_name": container_name,
                "hostname": host_name,
                "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                "restart": "always",
                "environment": {
                    "ME_CONFIG_BASICAUTH_USERNAME": env["ME_CONFIG_BASICAUTH_USERNAME"],
                    "ME_CONFIG_BASICAUTH_PASSWORD": env["ME_CONFIG_BASICAUTH_PASSWORD"],
                    "ME_CONFIG_OPTIONS_EDITORTHEME": env[
                        "ME_CONFIG_OPTIONS_EDITORTHEME"
                    ],
                    "ME_CONFIG_MONGODB_SERVER": env["ME_CONFIG_MONGODB_SERVER"],
                    "ME_CONFIG_MONGODB_PORT": str(env["ME_CONFIG_MONGODB_PORT"]).format(
                        MONGO_DB_PORT_CONTAINER=env["MONGO_DB_PORT_CONTAINER"]
                    ),
                    "ME_CONFIG_MONGODB_URL": str(env["ME_CONFIG_MONGODB_URL"]).format(
                        MONGO_DB_PORT_CONTAINER=env["MONGO_DB_PORT_CONTAINER"]
                    ),
                },
                "depends_on": [
                    "mongodb-10-2",
                ],
                **copy.deepcopy(network_dict),
                # Todo
                #  "healthcheck": {
                #      "test": ["CMD", "wget", "-S", f"http://0.0.0.0:{env_10_2.get('MONGO_EXPRESS_PORT_CONTAINER')}"],
                #      "interval": "10s",
                #      "timeout": "2s",
                #      "retries": "3",
                #  },
                **copy.deepcopy(ports_dict),
            },
        },
    }
    # @formatter:on

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```shell\n{docker_yaml}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
)
def script_chown_mongodb(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, str]] | AssetMaterialization, None, None]:

    ret = dict()

    ret["exe"] = shutil.which("bash")
    ret["script"] = str()

    mongo_db_dir_host = pathlib.Path(
        env[f"DATABASE_INSTALL_DESTINATION_{'__'.join(ASSET_HEADER['key_prefix'])}"]
    )

    # sudo chown 101:65534 DeadlineDatabase10
    # Concept: /usr/bin/sshpass -eENV_VAR /usr/bin/ssh "echo $ENV_VAR | sudo -S <cmd>"
    # Because shutil.chown cannot sudo

    mongo_uid = 101
    mongo_gid = 65534

    # @formatter:off
    ret["script"] += "#!/bin/bash\n"
    ret["script"] += "\n"
    # ret["script"] += f"{shutil.which('sshpass')} -eSSH_PASS ssh {env_10_2['SSH_USER']}@{env_10_2['SSH_HOST']} \"echo $SSH_PASS | sudo -S chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()}\"\n"
    ret[
        "script"
    ] += f"echo $SUDO_PASS | sudo -S -k /usr/bin/chown {mongo_uid}:{mongo_gid} {mongo_db_dir_host.as_posix()};\n"
    ret["script"] += "\n"
    ret["script"] += "echo Success;\n"
    ret["script"] += "exit 0;\n"
    # @formatter:on

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
            "script_chown": MetadataValue.md(f"```shell\n{ret['script']}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "script_chown_mongodb_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "script_chown_mongodb"]),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_mongodb(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    script_chown_mongodb_10_2: dict[str, str],  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{env['MONGO_DB_PORT_HOST']}:{env['MONGO_DB_PORT_CONTAINER']}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    # image = "docker.io/mongodb/mongodb-community-server:4.4-ubuntu2004"

    # cmd_docker_run = [
    #     shutil.which("docker"),
    #     "run",
    #     "--rm",
    #     "--interactive",
    #     "--tty",
    #     image,
    #     "/bin/bash",
    # ]

    volumes_dict = {"volumes": []}

    mongo_db_dir_host = pathlib.Path(
        env[f"DATABASE_INSTALL_DESTINATION_{'__'.join(ASSET_HEADER['key_prefix'])}"]
    )
    mongo_db_dir_host.mkdir(parents=True, exist_ok=True)

    stdout_stderr = {
        "stdout": MetadataValue.md(f"```shell\nNone\n```"),
        "stderr": MetadataValue.md(f"```shell\nNone\n```"),
    }

    if not MONGODB_INSIDE_CONTAINER:

        if bool(script_chown_mongodb_10_2["script"]):

            context.log.info(f"Setting ownership of {mongo_db_dir_host.as_posix()}...")

            proc = subprocess.Popen(
                script_chown_mongodb_10_2["exe"],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                stdin=subprocess.PIPE,
                env={
                    "SUDO_PASS": EnvVar("SUDO_PASS").get_value(),
                },
            )

            stdout, stderr = proc.communicate(
                input=script_chown_mongodb_10_2["script"].encode(),
            )

            stdout_stderr = {
                "stdout": MetadataValue.md(
                    f"```shell\n{stdout.decode(encoding='utf-8')}\n```"
                ),
                "stderr": MetadataValue.md(
                    f"```shell\n{stderr.decode(encoding='utf-8')}\n```"
                ),
            }

            # helpers.iterate_fds(
            #     (
            #         proc.stderr,
            #         proc.stdout,
            #     ),
            #     (
            #         context.log.warning,
            #         context.log.info,
            #     )
            # )

        volumes_dict["volumes"].insert(
            0,
            f"{mongo_db_dir_host.as_posix()}:{env['DEFAULT_DBPATH_CONTAINER']}",
        )

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=pathlib.Path(env["DOCKER_COMPOSE"]),
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
        ]
    }

    service_name = "mongodb-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_MONGODB"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    docker_dict = {
        "services": {
            service_name: {
                "image": "docker.io/mongodb/mongodb-community-server:4.4-ubuntu2004",
                "container_name": container_name,
                "hostname": host_name,
                "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                "restart": "always",
                "command": [
                    "--port",
                    env["MONGO_DB_PORT_CONTAINER"],
                    "--dbpath",
                    f"{env['DEFAULT_DBPATH_CONTAINER']}",
                    "--bind_ip_all",
                    "--noauth",
                    "--storageEngine",
                    "wiredTiger",
                    "--tlsMode",
                    "disabled",
                ],
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```shell\n{docker_yaml}\n```"),
            # "cmd_docker_run": MetadataValue.path(cmd_list_to_str(cmd_docker_run)),
            "env": MetadataValue.json(env),
            **stdout_stderr,
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_rcs_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinercs",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "deadline_command_compose_rcs_runner_10_2": AssetIn(
            AssetKey(
                [*ASSET_HEADER["key_prefix"], "deadline_command_compose_rcs_runner"]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_rcs_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    build: dict,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_rcs_runner_10_2: list,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:
    """ """

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{env['RCS_HTTP_PORT_HOST']}:{env['RCS_HTTP_PORT_CONTAINER']}",
                # Todo:
                #  - [ ] Expose OpenStudioLandscapes standard Ports (https://docs.thinkboxsoftware.com/products/deadline/10.2/1_User%20Manual/manual/considerations.html#firewall-anti-virus-security-considerations)
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{env['REPOSITORY_INSTALL_DESTINATION_%s' % '__'.join(ASSET_HEADER['key_prefix'])]}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=pathlib.Path(env["DOCKER_COMPOSE"]),
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
        ]
    }

    service_name = "deadline-rcs-runner-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_RCS_RUNNER"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                "restart": "always",
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s" % (build["image_prefixes"], build["image_name"], build["image_tags"][0]),
                "depends_on": {
                    "repository-installer-10-2": {
                        "condition": "service_completed_successfully",
                    },
                },
                "command": deadline_command_compose_rcs_runner_10_2,
                "healthcheck": {
                    "test": [
                        "CMD",
                        "curl",
                        "-f",
                        f"http://localhost:{env['RCS_HTTP_PORT_CONTAINER']}",
                    ],
                    "interval": "10s",
                    "timeout": "2s",
                    "retries": "3",
                },
                **copy.deepcopy(network_dict),
                **copy.deepcopy(ports_dict),
                **copy.deepcopy(volumes_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
            "env_10_2": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_pulse_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinepulse",
        "-nogui",
        "-nosplash",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_pulse_runner_10_2": AssetIn(
            AssetKey(
                [*ASSET_HEADER["key_prefix"], "deadline_command_compose_pulse_runner"]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_pulse_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    build: dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_pulse_runner_10_2: list,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:
    """ """

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{env['REPOSITORY_INSTALL_DESTINATION_%s' % '__'.join(ASSET_HEADER['key_prefix'])]}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=pathlib.Path(env["DOCKER_COMPOSE"]),
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
        ]
    }

    service_name = "deadline-pulse-runner-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_PULSE_RUNNER"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    if DISABLE_LOCAL_PULSE:

        docker_dict = {}

    else:

        docker_dict = {
            "services": {
                service_name: {
                    "container_name": container_name,
                    "hostname": host_name,
                    "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                    "restart": "always",
                    # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                    # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s" % (build["image_prefixes"], build["image_name"], build["image_tags"][0]),
                    "depends_on": {
                        "deadline-rcs-runner-10-2": {
                            "condition": "service_started",
                        },
                    },
                    **copy.deepcopy(network_dict),
                    **copy.deepcopy(volumes_dict),
                    **copy.deepcopy(ports_dict),
                    "command": deadline_command_compose_pulse_runner_10_2,
                },
            },
        }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
            "env_10_2": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_worker_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlineworker",
        "-nogui",
        "-nosplash",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_worker_runner_10_2": AssetIn(
            AssetKey(
                [*ASSET_HEADER["key_prefix"], "deadline_command_compose_worker_runner"]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_worker_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    build: dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_worker_runner_10_2: list,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:
    """ """

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {"ports": []}
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{env['REPOSITORY_INSTALL_DESTINATION_%s' % '__'.join(ASSET_HEADER['key_prefix'])]}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    service_name = "deadline-worker-runner-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_WORKER_RUNNER"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    if DISABLE_LOCAL_WORKER:

        docker_dict = {}

    else:

        docker_dict = {
            "services": {
                service_name: {
                    "container_name": container_name,
                    "hostname": host_name,
                    "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                    "restart": "always",
                    # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                    # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s" % (build["image_prefixes"], build["image_name"], build["image_tags"][0]),
                    "depends_on": {
                        "deadline-rcs-runner-10-2": {
                            "condition": "service_started",
                        },
                    },
                    **copy.deepcopy(network_dict),
                    **copy.deepcopy(volumes_dict),
                    **copy.deepcopy(ports_dict),
                    "command": deadline_command_compose_worker_runner_10_2,
                },
            },
        }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
    },
    description="This executes the OpenStudioLandscapes Repository Installer. "
    "Needs to be done only once.",
)
def deadline_command_compose_webservice_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list[str]] | AssetMaterialization, None, None]:
    """ """

    deadline_command = [
        "/opt/Thinkbox/Deadline10/bin/deadlinewebservice",
    ]

    yield Output(deadline_command)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(deadline_command),
            "deadline_command": MetadataValue.path(
                " ".join(shlex.quote(s) for s in deadline_command)
            ),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "env": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "env"]),
        ),
        "build": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "build_docker_image_client"]),
        ),
        "deadline_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "deadline_ini"]),
        ),
        "connection_ini_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "connection_ini"]),
        ),
        "deadline_command_compose_webservice_runner_10_2": AssetIn(
            AssetKey(
                [
                    *ASSET_HEADER["key_prefix"],
                    "deadline_command_compose_webservice_runner",
                ]
            ),
        ),
        "compose_networks_10_2": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_networks"]),
        ),
    },
)
def compose_webservice_runner(
    context: AssetExecutionContext,
    env: dict,  # pylint: disable=redefined-outer-name
    build: dict,  # pylint: disable=redefined-outer-name
    deadline_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    connection_ini_10_2: pathlib.Path,  # pylint: disable=redefined-outer-name
    deadline_command_compose_webservice_runner_10_2: list,  # pylint: disable=redefined-outer-name
    compose_networks_10_2: dict,  # pylint: disable=redefined-outer-name
) -> Generator[Output[dict[str, dict[str, dict]]] | AssetMaterialization, None, None]:
    """ """

    network_dict = {}
    ports_dict = {}

    if "networks" in compose_networks_10_2:
        network_dict = {
            "networks": list(compose_networks_10_2.get("networks", {}).keys())
        }
        ports_dict = {
            "ports": [
                f"{env['WEBSERVICE_HTTP_PORT_HOST']}:{env['WEBSERVICE_HTTP_PORT_CONTAINER']}",
            ]
        }
    elif "network_mode" in compose_networks_10_2:
        network_dict = {"network_mode": compose_networks_10_2["network_mode"]}
        ports_dict = {}
    else:
        network_dict = {}
        ports_dict = {}

    volumes_dict = {
        "volumes": [
            f"{deadline_ini_10_2.as_posix()}:/var/lib/Thinkbox/Deadline10/deadline.ini:ro",
            f"{connection_ini_10_2.as_posix()}:/opt/Thinkbox/DeadlineRepository10/settings/connection.ini:ro",
            f"{env['REPOSITORY_INSTALL_DESTINATION_%s' % '__'.join(ASSET_HEADER['key_prefix'])]}:/opt/Thinkbox/DeadlineRepository10",
        ]
    }

    # For portability, convert absolute volume paths to relative paths

    _volume_relative = []

    for v in volumes_dict["volumes"]:

        host, container = v.split(":", maxsplit=1)

        volume_dir_host_rel_path = get_relative_path_via_common_root(
            context=context,
            path_src=pathlib.Path(env["DOCKER_COMPOSE"]),
            path_dst=pathlib.Path(host),
            path_common_root=pathlib.Path(env["DOT_LANDSCAPES"]),
        )

        _volume_relative.append(
            f"{volume_dir_host_rel_path.as_posix()}:{container}",
        )

    volumes_dict = {
        "volumes": [
            *_volume_relative,
        ]
    }

    service_name = "deadline-webservice-runner-10-2"
    container_name = "--".join([service_name, env.get("LANDSCAPE", "default")])
    host_name = ".".join(
        [
            env["HOSTNAME_WEBSERVICE_RUNNER"] or service_name,
            env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
        ]
    )

    docker_dict = {
        "services": {
            service_name: {
                "container_name": container_name,
                "hostname": host_name,
                "domainname": env["OPENSTUDIOLANDSCAPES__DOMAIN_LAN"],
                "restart": "always",
                # "image": "${DOT_OVERRIDES_REGISTRY_NAMESPACE:-docker.io/openstudiolandscapes}/%s:%s"
                # % (build["image_name"], build["image_tags"][0]),
                "image": "%s%s:%s" % (build["image_prefixes"], build["image_name"], build["image_tags"][0]),
                "depends_on": {
                    "deadline-rcs-runner-10-2": {
                        "condition": "service_started",
                    },
                },
                "healthcheck": {
                    "test": [
                        "CMD",
                        "curl",
                        "-f",
                        f"http://localhost:{env['WEBSERVICE_HTTP_PORT_CONTAINER']}",
                    ],
                    "interval": "10s",
                    "timeout": "2s",
                    "retries": "3",
                },
                **copy.deepcopy(network_dict),
                "command": deadline_command_compose_webservice_runner_10_2,
                **copy.deepcopy(volumes_dict),
                **copy.deepcopy(ports_dict),
            },
        },
    }

    docker_yaml = yaml.dump(docker_dict)

    yield Output(docker_dict)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(docker_dict),
            "docker_dict": MetadataValue.md(
                f"```json\n{json.dumps(docker_dict, indent=2)}\n```"
            ),
            "docker_yaml": MetadataValue.md(f"```yaml\n{docker_yaml}\n```"),
            "env": MetadataValue.json(env),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={
        "compose_webservice_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_webservice_runner"]),
        ),
        "compose_worker_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_worker_runner"]),
        ),
        "compose_pulse_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_pulse_runner"]),
        ),
        "compose_rcs_runner": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_rcs_runner"]),
        ),
        "compose_mongo_express": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongo_express"]),
        ),
        "compose_mongodb": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_mongodb"]),
        ),
        "compose_repository": AssetIn(
            AssetKey([*ASSET_HEADER["key_prefix"], "compose_repository"]),
        ),
    },
)
def compose_maps(
    context: AssetExecutionContext,
    **kwargs,  # pylint: disable=redefined-outer-name
) -> Generator[Output[list[dict]] | AssetMaterialization, None, None]:

    ret = list(kwargs.values())

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={},
)
def cmd_extend(
    context: AssetExecutionContext,
) -> Generator[Output[list[Any]] | AssetMaterialization | Any, Any, None]:

    ret = []

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
        },
    )


@asset(
    **ASSET_HEADER,
    ins={},
)
def cmd_append(
    context: AssetExecutionContext,
) -> Generator[Output[dict[str, list[Any]]] | AssetMaterialization | Any, Any, None]:

    ret = {"cmd": [], "exclude_from_quote": []}

    yield Output(ret)

    yield AssetMaterialization(
        asset_key=context.asset_key,
        metadata={
            "__".join(context.asset_key.path): MetadataValue.json(ret),
        },
    )
