# Base Information
group_name: "OpenStudioLandscapes_Deadline_10_2"
key_prefixes:
  - "OpenStudioLandscapes_Deadline_10_2"

#compose_scope: "default"

# Not enabled by default because this Feature
# has some basic requirements, such as
# the installers
#enabled: false

deadline_10_2_installer_aws_portal_link: "/home/michael/git/repos/OpenStudioLandscapes/.features/OpenStudioLandscapes-Deadline-10-2/.payload/bin/AWSPortalLink-1.2.1.0-linux-x64-installer.run"
deadline_10_2_installer_deadline_client: "/home/michael/git/repos/OpenStudioLandscapes/.features/OpenStudioLandscapes-Deadline-10-2/.payload/bin/DeadlineClient-10.2.1.1-linux-x64-installer.run"
deadline_10_2_installer_deadline_repository: "/home/michael/git/repos/OpenStudioLandscapes/.features/OpenStudioLandscapes-Deadline-10-2/.payload/bin/DeadlineRepository-10.2.1.1-linux-x64-installer.run"

#deadline_10_2_repository_install_destination: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/data/opt/Thinkbox/DeadlineRepository10"
#deadline_10_2_database_install_destination: "{DOT_LANDSCAPES}/{LANDSCAPE}/{FEATURE}/data/opt/Thinkbox/DeadlineDatabase10"

#deadline_10_2_RCS_HTTP_PORT_HOST: 8888
#deadline_10_2_RCS_HTTP_PORT_CONTAINER: 8888
#
#deadline_10_2_WEBSERVICE_HTTP_PORT_HOST: 8899
#deadline_10_2_WEBSERVICE_HTTP_PORT_CONTAINER: 8899
#
#deadline_10_2_LAUNCHER_LISTENING_PORT: 17000
#
#deadline_10_2_AUTO_CONFIGURATION_PORT: 17001
#
#deadline_10_2_SLAVE_STARTUP_PORT: 17003
#
#deadline_10_2_LICENSE_FORWARDER_LISTENING_PORT: 17003
#
#deadline_10_2_APPLICATION_STARTUP_PORT: 17006

# MongoDB

#deadline_10_2_MONGO_DB_HOST: "mongodb-10-2"
#deadline_10_2_MONGO_DB_NAME: "deadline10db"
#deadline_10_2_DEFAULT_DBPATH_CONTAINER: "/data/db"
#deadline_10_2_MONGO_EXPRESS_PORT_HOST: 8181
#deadline_10_2_MONGO_EXPRESS_PORT_CONTAINER: 8081
#deadline_10_2_MONGO_DB_PORT_HOST: 21017
#deadline_10_2_MONGO_DB_PORT_CONTAINER: 21017

# Mongo Express

#deadline_10_2_ME_CONFIG_BASICAUTH_USERNAME: "web"
#deadline_10_2_ME_CONFIG_BASICAUTH_PASSWORD: "web"
#deadline_10_2_ME_CONFIG_OPTIONS_EDITORTHEME: "darcula"
#deadline_10_2_ME_CONFIG_MONGODB_SERVER: "mongodb-10-2"
#deadline_10_2_ME_CONFIG_MONGODB_URL: "mongodb://admin:pass@localhost:21017/db?ssl=false"
#deadline_10_2_ME_CONFIG_MONGODB_PORT: 21017